name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.2", "jruby-9.4.6"]
        rails: ["6.1.7", "7.2.1"]
        grape-swagger: ["1.6.1", "2.0.2"]
        include:
          - ruby: "2.7"
            rails: "6.1.7"
            grape-swagger: "1.6.1"
          - ruby: "3.0"
            rails: "6.1.7"
            grape-swagger: "1.6.1"
    env:
      GRAPE_SWAGGER_VERSION: ${{ matrix.grape-swagger }}
      RAILS_VERSION: ${{ matrix.rails }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Print Bundler Versions
        run: bundle show
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: "111.0.1"
      - uses: browser-actions/setup-geckodriver@latest
        with:
          geckodriver-version: "0.32.2"
      - uses: coactions/setup-xvfb@v1
        with:
          run: bundle exec rake spec
